### ISSUE TITLE
加载的网页如何打开相机，请大佬指导，谢谢

### ISSUE THREAD

**Issue by lichao3140** [LZ9/JsBridgeKt#1]
请问使用您这WebView加载H5页面，里面有打开相机，目前打开相机失败，改如何修改？

**Comment by LZ9** [comment]
@lichao3140 你好，可以详细说一下你使用的安卓版本和具体的代码步骤吗？

**Comment by lichao3140** [comment]
看到日志会出现这个：[INFO:CONSOLE(27)] "Uncaught TypeError: Cannot read property 'callHandler' of undefined"  要如何处理，在android本地加载html页面没这问题

**Comment by LZ9** [comment]
@lichao3140 这个报错是否是因为前端没有引用【JsBridge.js】这个文件，callHandler的定义在这个文件里
